### ISSUE TITLE
getting a module mismatch on msibacklight -k on 

### ISSUE THREAD

**Issue by pariosa** [Kwaadpepper/msi-keyboard-CLI#19]
Error: Module version mismatch. Expected 46, got 48.
    at Error (native)
    at Object.Module._extensions..node (module.js:435:18)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/{user}/.msi-klm/node_modules/node-hid/nodehid.js:9:15)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)

**Comment by Kwaadpepper** [comment]
This is related to the version of node.js you are using it is too far different from the one used to build node-hid parts. Maybe try to update your node.js version.

**Comment by pariosa** [comment]
I tried reverting my node version back to the version in the readme 0.10.25, and recieved the same error.

`$: sudo msikeyboard -c green                                                  

$: module.js:435                                                              
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: Module version mismatch. Expected 46, got 48.
    at Error (native)
    at Object.Module._extensions..node (module.js:435:18)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/msi-keyboard-cli/node_modules/node-hid/nodehid.js:9:15)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)

$: which node                                                                 
/home/{user}/.nvm/v0.10.25/bin/node
$: node -v                                                                    
v0.10.25
`

**Comment by pariosa** [comment]
module.js:356
  Module._extensions[extension](this, filename);
                               ^
Error: /usr/local/lib/node_modules/msi-keyboard-cli/node_modules/node-hid/build/HID/Release/HID.node: undefined symbol: node_module_register
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/msi-keyboard-cli/node_modules/node-hid/nodehid.js:9:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)


i uninstalled node and reinstalled version 0.10.25 and i'm still getting this error..
