### ISSUE TITLE
ERROR: Could not locate the bindings file...

### ISSUE THREAD

**Issue by raedeus** [Kwaadpepper/msi-keyboard-CLI#22]
Hello there,

Another installation attempt on Arch Linux. Newest build. Followed the installations steps exactly (pretty simple to follow really) and on entering "sudo msikeyboard -c green" I get the following error:

[raedeus@[REDACTED]~]$ sudo msikeyboard -c green
[raedeus@[REDACTED] ~]$ /usr/lib/node_modules/msi-keyboard-cli/node_modules/bindings/bindings.js:96
  throw err
  ^

Error: Could not locate the bindings file. Tried:
 → /usr/lib/node_modules/msi-keyboard-cli/node_modules/node-hid/build/HID.node
 → /usr/lib/node_modules/msi-keyboard-cli/node_modules/node-hid/build/Debug/HID.node
 → /usr/lib/node_modules/msi-keyboard-cli/node_modules/node-hid/build/Release/HID.node
 → /usr/lib/node_modules/msi-keyboard-cli/node_modules/node-hid/out/Debug/HID.node
 → /usr/lib/node_modules/msi-keyboard-cli/node_modules/node-hid/Debug/HID.node
 → /usr/lib/node_modules/msi-keyboard-cli/node_modules/node-hid/out/Release/HID.node
 → /usr/lib/node_modules/msi-keyboard-cli/node_modules/node-hid/Release/HID.node
 → /usr/lib/node_modules/msi-keyboard-cli/node_modules/node-hid/build/default/HID.node
 → /usr/lib/node_modules/msi-keyboard-cli/node_modules/node-hid/compiled/8.7.0/linux/x64/HID.node
    at bindings (/usr/lib/node_modules/msi-keyboard-cli/node_modules/bindings/bindings.js:93:9)
    at Object.<anonymous> (/usr/lib/node_modules/msi-keyboard-cli/node_modules/node-hid/nodehid.js:5:34)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/lib/node_modules/msi-keyboard-cli/node_modules/msi-keyboard/lib/findKeyboard.js:1:73)

Not sure if this has to do with symlinking node or not as I remember having to do that before but I am not sure this is the same context.

Any help would be appreciated.

MSI GHOST PRO 6QE

Arch uses libusb as a single package with *-dev stuff in it I guess so I don't think this is a dependency thing as npm already installed everything.

Thanks,

Raedeus

**Comment by raedeus** [comment]
I am getting a sneaking suspicion that this is no longer maintained.... :-|

**Comment by Kwaadpepper** [comment]
Sorry I don't have time to maintain this but it seems errors don't come from this project but msi-keyboard (on github) if you search in closed issues you may find some answers. This may be an issue with node-hid also.

**Comment by drmuelr** [comment]
@raedeus Did you have any luck resolving this? I'm hitting the same issue on Ubuntu 18.04, and didn't find anything in the parent project, either.

**Comment by raedeus** [comment]
Hey @drmuelr sorry I didn't respond earlier. I believe this was an issue with node-hid. I had to roll my version back.
