### ISSUE TITLE
Error: could not send feature report to device

### ISSUE THREAD

**Issue by betterphp** [Kwaadpepper/msi-keyboard-CLI#6]
After upgrading to Ubuntu 16.04 an exception is thrown when setting the backlight colour

```
jacek@jacek-home-laptop: ~ $ sudo msikeyboard left red high 0 middle blue high 0 right green high 0
/usr/local/lib/node_modules/msi-keyboard-cli/node_modules/msi-keyboard/lib/setColor.js:24
    keyboard.sendFeatureReport(activate);
             ^

Error: could not send feature report to device
    at Error (native)
    at module.exports (/usr/local/lib/node_modules/msi-keyboard-cli/node_modules/msi-keyboard/lib/setColor.js:24:11)
    at HID.board.color (/usr/local/lib/node_modules/msi-keyboard-cli/node_modules/msi-keyboard/lib/findKeyboard.js:12:3)
    at /usr/local/lib/node_modules/msi-keyboard-cli/msi-keyboard-CLI.js:348:18
    at FSReqWrap.cb [as oncomplete] (fs.js:212:19)
```

**Comment by hashcashier** [comment]
Your OS upgrade must have also updated your node version. This is an issue with the dependency node-hid: https://github.com/node-hid/node-hid/issues/118

**Comment by betterphp** [comment]
Seems to be working fine after https://github.com/stevelacy/msi-keyboard/issues/40

Thanks @rami-khalil <3
